name: changes

on:
  schedule:
    - cron:  '*/15 * * * *'

defaults:
  run:
    working-directory: ./

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 2

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: checkout
        uses: actions/checkout@v2

      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install --upgrade microprediction
            pip install --upgrade getjson
      - name: Run the model 
        env:
          WRITE_KEY: ${{ secrets.WRITE_KEY }}
        run: |
          python set.py
